import{FaceLandmarker,ImageSegmenter,FilesetResolver}from'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm';
const $=id=>document.getElementById(id),video=$('video'),overlay=$('overlay'),ctx=overlay.getContext('2d'),startBtn=$('scanBtn'),stopBtn=$('stopBtn'),cameraSwitch=$('cameraSwitch'),cameraCard=$('cameraCard'),resultCard=$('resultCard'),resultIcon=$('resultIcon'),resultTitle=$('resultTitle'),resultReason=$('resultReason'),cameraMessage=$('cameraMessage'),statusPill=$('statusPill'),confidence=$('confidence');
const checks={position:$('positionCheck'),fringe:$('fringeCheck'),ear:$('earCheck'),top:$('topCheck')};let stream=null,landmarker=null,segmenter=null,lastVideoTime=-1,facingMode='environment',cameraStarted=false,aiReady=false,checking=false,stable=0,missing=0,samples=[],lastSeg=0,busy=false;
const MODEL='https://storage.googleapis.com/mediapipe-models/image_segmenter/selfie_multiclass_256x256/float32/latest/selfie_multiclass_256x256.tflite';
function mark(el,state,text){el.textContent=text||(state==='pass'?'✓':state==='warn'?'UNSURE':state==='review'?'CHECK':'—');el.style.color=state==='pass'?'#34d399':state==='warn'?'#fbbf24':state==='review'?'#f87171':'#94a3b8'}
function reset(title='Waiting for student',reason='Point the camera at one student.'){cameraCard.classList.remove('pass','review','warn');resultCard.className='result-card neutral';resultIcon.textContent='◎';resultTitle.textContent=title;resultReason.textContent=reason;confidence.classList.add('hidden');Object.values(checks).forEach(x=>mark(x,'neutral'));samples=[];stable=0}
async function initAI(){try{const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm');landmarker=await FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numFaces:2,minFaceDetectionConfidence:.6,minFacePresenceConfidence:.6,minTrackingConfidence:.6});segmenter=await ImageSegmenter.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL,delegate:'CPU'},runningMode:'VIDEO',outputCategoryMask:true,outputConfidenceMasks:false});aiReady=true;statusPill.textContent='HAIR AI READY';startBtn.disabled=false;resultTitle.textContent='Ready';resultReason.textContent='Tap Start HAIR check once, then move from student to student.';cameraMessage.innerHTML='<strong>Ready</strong><span>Tap Start HAIR check</span>'}catch(e){console.error(e);statusPill.textContent='AI ERROR';resultTitle.textContent='AI could not load';resultReason.textContent='Reload the page and check your connection.'}}
async function startCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:1280},height:{ideal:1920}},audio:false});video.srcObject=stream;await video.play();cameraStarted=true}
function stopCamera(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;cameraStarted=checking=false;video.srcObject=null;ctx.clearRect(0,0,overlay.width,overlay.height)}
const avg=(lm,ids)=>{let x=0,y=0;ids.forEach(i=>{x+=lm[i].x;y+=lm[i].y});return{x:x/ids.length,y:y/ids.length}};
function geometry(lm){const le=avg(lm,[33,133,159,145]),re=avg(lm,[362,263,386,374]),lb=avg(lm,[70,63,105,66,107]),rb=avg(lm,[336,296,334,293,300]),lear=lm[234],rear=lm[454],chin=lm[152],fore=lm[10],nose=lm[1];const eyeD=Math.abs(re.x-le.x),faceH=Math.abs(chin.y-fore.y),cx=(le.x+re.x)/2,eyeY=(le.y+re.y)/2,straight=Math.abs(le.y-re.y)<.045;return{le,re,lb,rb,lear,rear,chin,fore,nose,eyeD,faceH,valid:cx>.25&&cx<.75&&eyeY>.20&&eyeY<.65&&eyeD>.095&&faceH>.23&&straight}}
function maskRatio(mask,mw,mh,x0,y0,x1,y1){const X0=Math.max(0,Math.floor(x0*mw)),X1=Math.min(mw,Math.ceil(x1*mw)),Y0=Math.max(0,Math.floor(y0*mh)),Y1=Math.min(mh,Math.ceil(y1*mh));let hair=0,n=0;for(let y=Y0;y<Y1;y+=2)for(let x=X0;x<X1;x+=2){if(mask[y*mw+x]===1)hair++;n++}return n?hair/n:0}
function analyseMask(g,res){const m=res.categoryMask,mask=m.getAsUint8Array(),mw=m.width,mh=m.height,browY=(g.lb.y+g.rb.y)/2,pad=g.eyeD*.16;const fringe=maskRatio(mask,mw,mh,g.le.x-pad,browY-.025,g.re.x+pad,browY+.018);const earL=maskRatio(mask,mw,mh,g.lear.x-.035,g.lear.y-.055,g.lear.x+.035,g.lear.y+.06),earR=maskRatio(mask,mw,mh,g.rear.x-.035,g.rear.y-.055,g.rear.x+.035,g.rear.y+.06);let topEdge=g.fore.y;for(let y=g.fore.y;y>Math.max(.01,g.fore.y-g.faceH*.72);y-=.01){if(maskRatio(mask,mw,mh,g.fore.x-g.eyeD*.72,y-.008,g.fore.x+g.eyeD*.72,y+.008)>.22)topEdge=y}const top=(g.fore.y-topEdge)/g.faceH;return{fringe,ear:Math.max(earL,earR),top,topEdge}}
function vote(values,threshold){const hits=values.filter(v=>v>threshold).length,p=hits/values.length,mean=values.reduce((a,b)=>a+b,0)/values.length;return{bad:p>=.6,uncertain:p>.25&&p<.6,confidence:Math.round(Math.max(p,1-p)*100),mean}}
function consensus(){const f=vote(samples.map(s=>s.fringe),.18),e=vote(samples.map(s=>s.ear),.24),t=vote(samples.map(s=>s.top),.43);return{f,e,t,bad:f.bad||e.bad||t.bad,uncertain:f.uncertain||e.uncertain||t.uncertain,confidence:Math.min(f.confidence,e.confidence,t.confidence)}}
function draw(g,c){overlay.width=video.videoWidth;overlay.height=video.videoHeight;ctx.clearRect(0,0,overlay.width,overlay.height);const W=overlay.width,H=overlay.height,line=(x1,y1,x2,y2,state)=>{ctx.strokeStyle=state==='bad'?'#ef4444':state==='warn'?'#fbbf24':'#22c55e';ctx.lineWidth=Math.max(4,W/240);ctx.beginPath();ctx.moveTo(x1*W,y1*H);ctx.lineTo(x2*W,y2*H);ctx.stroke()};const state=v=>v?.bad?'bad':v?.uncertain?'warn':'ok';line(g.le.x-.05,(g.lb.y+g.rb.y)/2,g.re.x+.05,(g.lb.y+g.rb.y)/2,state(c?.f));line(g.lear.x,g.lear.y-.065,g.lear.x,g.lear.y+.065,state(c?.e));line(g.rear.x,g.rear.y-.065,g.rear.x,g.rear.y+.065,state(c?.e));line(g.fore.x-g.eyeD*.72,g.fore.y-g.faceH*.43,g.fore.x+g.eyeD*.72,g.fore.y-g.faceH*.43,state(c?.t))}
function show(g,c){const state=v=>v.bad?'review':v.uncertain?'warn':'pass';mark(checks.position,'pass','✓');mark(checks.fringe,state(c.f));mark(checks.ear,state(c.e));mark(checks.top,state(c.t));const issues=[];if(c.f.bad)issues.push('fringe reaches eyebrow zone');if(c.e.bad)issues.push('hair reaches ear zone');if(c.t.bad)issues.push('top exceeds configured height');const warn=!issues.length&&c.uncertain;cameraCard.classList.remove('pass','review','warn');cameraCard.classList.add(issues.length?'review':warn?'warn':'pass');resultCard.className='result-card '+(issues.length?'review':warn?'warn':'pass');resultIcon.textContent=issues.length?'!':warn?'?':'✓';resultTitle.textContent=issues.length?'Teacher check':warn?'Unsure — teacher check':'Looks acceptable';resultReason.textContent=issues.length?issues.join(' • '):warn?'The AI did not get a consistent reading across frames.':'No configured hair threshold was triggered.';confidence.textContent=`Confidence ${c.confidence}% • ${samples.length} frames`;confidence.classList.remove('hidden');cameraMessage.innerHTML=issues.length?`<strong>CHECK</strong><span>${issues[0]}</span>`:warn?'<strong>UNSURE</strong><span>Teacher visual check recommended</span>':'<strong>PASS</strong><span>Move to next student</span>';draw(g,c)}
async function processHair(g,now){if(busy||now-lastSeg<130)return;busy=true;lastSeg=now;try{const r=segmenter.segmentForVideo(video,Math.floor(now));const s=analyseMask(g,r);samples.push(s);if(samples.length>12)samples.shift();if(samples.length>=7)show(g,consensus());else{resultTitle.textContent=`Analysing… ${samples.length}/7`;resultReason.textContent='Hold still while HAIR checks several frames.'}}catch(e){console.warn('Segmentation',e)}finally{busy=false}}
async function loop(now=performance.now()){if(!checking||!cameraStarted)return;if(video.readyState>=2&&video.currentTime!==lastVideoTime){lastVideoTime=video.currentTime;try{const r=landmarker.detectForVideo(video,now);const faces=r.faceLandmarks||[];if(faces.length>1){missing=0;stable=0;samples=[];mark(checks.position,'warn','1 PERSON');resultTitle.textContent='Multiple faces';resultReason.textContent='Keep only one student in the scan area.';cameraMessage.innerHTML='<strong>ONE STUDENT AT A TIME</strong><span>Move other faces out of frame</span>';ctx.clearRect(0,0,overlay.width,overlay.height)}else if(faces.length===1){missing=0;const g=geometry(faces[0]);if(!g.valid){stable=0;samples=[];mark(checks.position,'warn','Adjust');resultTitle.textContent='Reposition';resultReason.textContent='Move closer, centre the face and look straight at the camera.';cameraMessage.innerHTML='<strong>Adjust student</strong><span>Clear front-facing view needed</span>';draw(g,null)}else{stable++;mark(checks.position,'pass','✓');if(stable>4)await processHair(g,now);else{resultTitle.textContent='Face locked';resultReason.textContent='Hold still briefly.'}}}else{missing++;stable=0;if(missing>6){ctx.clearRect(0,0,overlay.width,overlay.height);reset();cameraMessage.innerHTML='<strong>Waiting for student</strong><span>Point camera at next student</span>'}}}catch(e){console.warn(e)}}requestAnimationFrame(loop)}
async function begin(){startBtn.disabled=true;startBtn.textContent='Starting…';try{await startCamera();checking=true;stable=missing=0;samples=[];statusPill.textContent='LIVE • HAIR AI';startBtn.classList.add('hidden');stopBtn.classList.remove('hidden');reset();cameraMessage.innerHTML='<strong>Waiting for student</strong><span>Point camera at a student</span>';requestAnimationFrame(loop)}catch(e){console.error(e);startBtn.disabled=false;startBtn.textContent='Start HAIR check';resultTitle.textContent='Camera unavailable';resultReason.textContent='Camera access is required for live checking.'}}
function end(){stopCamera();statusPill.textContent='HAIR AI READY';stopBtn.classList.add('hidden');startBtn.classList.remove('hidden');startBtn.disabled=false;startBtn.textContent='Start HAIR check';reset('Checking stopped','Tap Start HAIR check to resume.');cameraMessage.innerHTML='<strong>Camera off</strong><span>Tap Start HAIR check</span>'}
startBtn.onclick=begin;stopBtn.onclick=end;cameraSwitch.onclick=async()=>{facingMode=facingMode==='environment'?'user':'environment';if(cameraStarted){samples=[];await startCamera()}};window.addEventListener('pagehide',stopCamera);await initAI();